const OK_CODE = 200;
const OK_CREATE_CODE = 201;

const ERROR_VALIDATION_CODE = 400;
const ERROR_UNAUTHORIZED_CODE = 401;
const ERROR_FORBIDDEN_CODE = 403;
const ERROR_NOT_FOUND_CODE = 404;
const ERROR_CONFLICT_CODE = 409;

module.exports = {
  OK_CODE,
  OK_CREATE_CODE,
  ERROR_FORBIDDEN_CODE,
  ERROR_VALIDATION_CODE,
  ERROR_NOT_FOUND_CODE,
  ERROR_CONFLICT_CODE,
  ERROR_UNAUTHORIZED_CODE,
};
